In [8]:
# TensorFlow is an open source machine learning library
import tensorflow as tf
# NumPy is a math library
import numpy as np
# Matplotlib is a graphing library
import matplotlib.pyplot as plt
# math is Python's math library
import math

print("I am running on the TF version: ", tf.__version__)

I am running on the TF version:  2.4.1


In [9]:
# Shape of tensor
val_const = tf.constant([ [10, 11],
                        [12, 13],
                        [14, 15] ]                      
                     ) 
val_const.shape

TensorShape([3, 2])

In [10]:
print(val_const.dtype)

<dtype: 'int32'>


In [11]:
print(val_const)

tf.Tensor(
[[10 11]
 [12 13]
 [14 15]], shape=(3, 2), dtype=int32)


In [12]:
# Create a vector of 10 elements, TF2.0 default creates tensors with float32
print(tf.zeros(10))

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)


In [13]:
# Create a 2D array (10x10) with filled with 1s
# The input [10, 10] specifies the shape of the tensor to be created
print(tf.ones([10, 10]))

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(10, 10), dtype=float32)


In [14]:
# Create a vector of ones with the same elements  on axis 0 with rank 1
# of val_const which is a 2D tensor constant. It will create a vector.
# Note rank 0 is a scalar
print(tf.ones(val_const.shape[0]))	

tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)


In [15]:
# Create a vector of ones with the same number of rows as m_shape
print(tf.ones(val_const.shape[1]))

tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [16]:
# Create a vector of ones with the same number of rows as m_shape
# If you want to override the default float32, give the datatype
print(tf.ones(val_const.shape, dtype='int32'))

tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)


In [17]:
# Change type of data
val_float = tf.constant(3.123456789, tf.float32)
val_int = tf.cast(val_float, dtype=tf.int32)
print(val_float.dtype)
print(val_int.dtype)	

<dtype: 'float32'>
<dtype: 'int32'>


In [18]:
# It converts from tensor to numpy
print(val_float.numpy())
print(val_float.numpy())

3.1234567
3.1234567


In [19]:
# It converts from numpy to a tensor
npArr = np.zeros([2, 3], dtype='int32')
print(npArr)
tensor = tf.convert_to_tensor(npArr)
print(tensor)
print(type(tensor))

[[0 0 0]
 [0 0 0]]
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [20]:
print(val_float, val_int)

tf.Tensor(3.1234567, shape=(), dtype=float32) tf.Tensor(3, shape=(), dtype=int32)


In [21]:
x = tf.constant([2.0], dtype = tf.float32)
print(tf.sqrt(x))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)


In [22]:
# Add
tensor_a = tf.constant([[1, 2]], dtype = tf.int32)
tensor_b = tf.constant([[3, 4]], dtype = tf.int32)

tensor_add = tf.add(tensor_a, tensor_b)
print(tensor_add)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


In [23]:
# Multiply
tensor_multiply = tf.multiply(tensor_a, tensor_b)
print(tensor_multiply)	

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [24]:
# tf.get_variable(name = "", values, dtype, initializer)
# Create a Variable
my_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
my_variable = tf.Variable(my_tensor)
print(my_variable)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>


In [25]:
print("Shape: ", my_variable.shape)
print("DType: ", my_variable.dtype)
print("As NumPy: ", my_variable.numpy())

Shape:  (2, 2)
DType:  <dtype: 'float32'>
As NumPy:  [[1. 2.]
 [3. 4.]]


In [26]:
# Variables can be all kinds of types, just like tensors
bool_variable = tf.Variable([False, False, False, True])
print(bool_variable)
complex_variable = tf.Variable([5 + 4j, 6 + 1j])
print(complex_variable)

<tf.Variable 'Variable:0' shape=(4,) dtype=bool, numpy=array([False, False, False,  True])>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([5.+4.j, 6.+1.j])>


In [27]:
a = tf.Variable([2.0, 3.0])
# Create b based on the value of a
b = tf.Variable(a)
a.assign([5, 6])

# a and b are different
print(a.numpy())
print(b.numpy())

# There are other versions of assign
print(a.assign_add([2,3]).numpy())  # [7. 9.]
print(a.assign_sub([7,9]).numpy())  # [0. 0.]

[5. 6.]
[2. 3.]
[7. 9.]
[0. 0.]


In [28]:
print('my_tensor:\n', my_tensor)
# Create a and b; they will have the same name but will be backed by
# different tensors.
a = tf.Variable(my_tensor, name="Mark")
# A new variable with the same name, but different value
# Note that the scalar add is broadcast
b = tf.Variable(my_tensor + 1, name="Mark")

print('a:\n', a)
print('b:\n', b)
# These are elementwise-unequal, despite having the same name
print(a == b)

my_tensor:
 tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
a:
 <tf.Variable 'Mark:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>
b:
 <tf.Variable 'Mark:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>
tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)
